name: Build OpenWrt
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Installation golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - names: Installation xcaddy
        run: |
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - name: build
        run: |
          cd ~/
          xcaddy build master --with github.com/caddyserver/forwardproxy@caddy2
      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: caddy
          path: ~/

    