name: Build OpenWrt
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Installation depends
      uses: actions/setup-go@v1
        with:
          go-version: 1.18
    - name: build
      run: |
        cd ~/
        xcaddy build master --with github.com/caddyserver/forwardproxy@caddy2
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: caddy
        path: ~/

    