name: Build OpenWrt
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Installation depends
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint
        go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
    - name: build
      run: |
        cd ~/
        xcaddy build master --with github.com/caddyserver/forwardproxy@caddy2
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: caddy
        path: ~/

    